Use the last reported location for errors in parseExpr/parseStmt code
saem/vscode-nim pull request #71
Opened 2022-01-22 11:50 UTC by RSDuck

Consider these snippets:

```nim
import strformat
echo &"{test}"
```

```nim
import strformat

proc test[T](): T =
    result *= 2

proc miauz[T](): T =
    echo &"{test[string]()}"

miauz[int]()
```

Currently the diagonstics provider throws an exception with code like this because it cannot handle that there's no filename in the error log:

```
...\strformaterror.nim(2, 6) template/generic instantiation of `&` from here
(1, 1) Error: undeclared identifier: 'test'
candidates (edit distance, scope distance); see '--spellSuggest':
 (2, 4): 'lent' [type declared in C:\Nim\lib\system.nim(307, 6)]
 (2, 4): 'reset' [proc declared in C:\Nim\lib\system.nim(1000, 6)]
 (2, 4): 'set' [type declared in C:\Nim\lib\system.nim(300, 3)]
```

I was thinking about putting in some fake filename, I thought that could be confusing, so I settled with repeating the last reported location instead (see also the comment in the code for rationale).

In an idea world, it would create an virtual file where you could see the generated code with the error in it, though then again parseExpr/parseStmt aren't used that often in Nim.

Alternative ideas are welcome!

2022-01-23 09:23 UTC, saem requested changes
Better than before.

Noticed a code style thing, I like to avoid mutation where possible.

2022-01-23 09:23 UTC, saem commented on src/nimBuild.nim
> +      if file.toJs() == jsUndefined:
Instead how about lifting the predicate into the let, you can use the predicate and your unpacking to conditionally assign the three variable bits. That way no vars, decision and mutation are kept to a minimum.

2022-01-30 15:55 UTC, RSDuck commented
here we go

2022-01-30 20:48 UTC, saem approved these changes

2022-01-30 20:57 UTC, merged